### ISSUE TITLE
Stemming not working

### ISSUE THREAD

**Issue by lukaskoston** [ali-wetrill/FOMCTranscriptAnalysis#1]
Hi, 
I am trying to rebuild your code and as I am totally new in programming and python I have a question/ issue. While executing the part of stemming I always get some errors. I refer to this part of the code: 

FOMC19820202meetingStop.txt -> FOMC19820202meetingStopstemmed.txt
In [11]:
# i = 0
# for doc in sorted_transcripts:
#     !python porterstemmer.py {doc}
#     i += 1
#     print("File " + str(i) + " of " + str(len(sorted_transcripts)) + " Completed")
#     print(str(int(i * 100 / len(sorted_transcripts)))  + "%")
We will now re-re-adjust our sorted_transcripts list
In [12]:
# run all the adjusting of variable sorted_transcripts in order
mod_transcripts = []
for link in sorted_transcripts:
    mod_transcripts.append(str(link)[:-4] + "stemmed.txt")
sorted_transcripts = mod_transcripts
print("Number of Documents", len(sorted_transcripts))
Number of Documents 216

Most likely I think there is somewhere a mistake within these two lines: 
# for doc in sorted_transcripts:
#     !python porterstemmer.py {doc}

What do you think?

Would help me a lot if you help me out. 
As I mentioned, I am completely new in Programming, so I'm sorry if I miss something obvious for you.

All the best, 
Lukas

**Comment by lukaskoston** [comment]
My mistake

**Comment by ali-aka-ahmed** [comment]
Hi! No worries, just saw this - double checking did you make the fix? Would have to see your file directory, I'm guessing it's where the porterstemmer.py file is located or on this line:

```!python porterstemmer.py {doc}```
the ! is saying run the following line as if you were in terminal. The {doc} is taking the name of the doc in sorted_transcript and inserting it at the place. The curly braces tell the compiler 'don't interpret this literally (like run porterstemmer.py on some file called doc). Doc is a variable so first translate it'. You'll see that pattern a lot in frontend coding - where curly braces mean 'interpret this code first, run it, then run the outer line.'
